"""Add is_active column to machines

Revision ID: 12208e78e806
Revises: d94020ade21a
Create Date: 2026-06-23 22:23:39.480948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12208e78e806'
down_revision: Union[str, Sequence[str], None] = 'd94020ade21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'is_active')
    # ### end Alembic commands ###
