"""Add cost_margin to product_price_history

Revision ID: 12e3ca20ed83
Revises: 12208e78e806
Create Date: 2026-06-24 12:48:04.531994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e3ca20ed83'
down_revision: Union[str, Sequence[str], None] = '12208e78e806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_history', sa.Column('cost_margin', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_price_history', 'cost_margin')
    # ### end Alembic commands ###
