"""Add closed_by_id to DailyLogSession

Revision ID: 3578dbdb9e59
Revises: 4551254649f5
Create Date: 2026-07-27 18:13:25.951533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3578dbdb9e59'
down_revision: Union[str, Sequence[str], None] = '4551254649f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_log_sessions', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_log_sessions', 'users', ['closed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_log_sessions', type_='foreignkey')
    op.drop_column('daily_log_sessions', 'closed_by_id')
    # ### end Alembic commands ###
