"""add_is_paytm_linked_to_pump_accounts

Revision ID: 390fc7b221bd
Revises: 55655d4b983b
Create Date: 2026-07-04 18:10:43.254146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390fc7b221bd'
down_revision: Union[str, Sequence[str], None] = '55655d4b983b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pump_accounts', sa.Column('is_paytm_linked', sa.Boolean(), nullable=True))
    op.execute("UPDATE pump_accounts SET is_paytm_linked = FALSE")
    op.alter_column('pump_accounts', 'is_paytm_linked', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pump_accounts', 'is_paytm_linked')
    # ### end Alembic commands ###
