"""Add is_initialization to DailyLogSession

Revision ID: 454209646e83
Revises: 8afe28d8799b
Create Date: 2026-07-18 13:31:10.938037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454209646e83'
down_revision: Union[str, Sequence[str], None] = '8afe28d8799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('daily_log_sessions', sa.Column('is_initialization', sa.Boolean(), nullable=True))
    op.execute('UPDATE daily_log_sessions SET is_initialization = FALSE')
    op.alter_column('daily_log_sessions', 'is_initialization', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_log_sessions', 'is_initialization')
    # ### end Alembic commands ###
