"""Add pump accounts and daily collections

Revision ID: 55655d4b983b
Revises: 9e8368d391c1
Create Date: 2026-07-04 17:04:38.110272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55655d4b983b'
down_revision: Union[str, Sequence[str], None] = '9e8368d391c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_constant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pump_id', 'name', name='uq_pump_account_name')
    )
    op.create_index(op.f('ix_pump_accounts_id'), 'pump_accounts', ['id'], unique=False)
    op.create_table('daily_session_payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['daily_log_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'payment_method', name='uq_session_payment_method')
    )
    op.create_index(op.f('ix_daily_session_payments_id'), 'daily_session_payments', ['id'], unique=False)
    op.add_column('credit_transactions', sa.Column('pump_account_id', sa.Integer(), nullable=True))
    op.alter_column('credit_transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'credit_transactions', 'pump_accounts', ['pump_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.alter_column('credit_transactions', 'payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.drop_column('credit_transactions', 'pump_account_id')
    op.drop_index(op.f('ix_daily_session_payments_id'), table_name='daily_session_payments')
    op.drop_table('daily_session_payments')
    op.drop_index(op.f('ix_pump_accounts_id'), table_name='pump_accounts')
    op.drop_table('pump_accounts')
    # ### end Alembic commands ###
