"""add_dip_volume_and_variance_to_tanks

Revision ID: 5fa7542ce405
Revises: 12e3ca20ed83
Create Date: 2026-06-26 18:49:42.653242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa7542ce405'
down_revision: Union[str, Sequence[str], None] = '12e3ca20ed83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanks', sa.Column('actual_dip_volume', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('tanks', sa.Column('variance', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanks', 'variance')
    op.drop_column('tanks', 'actual_dip_volume')
    # ### end Alembic commands ###
