"""add prior period adjustment to daily log session

Revision ID: 8afe28d8799b
Revises: 9d842e480345
Create Date: 2026-07-18 12:08:54.875250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afe28d8799b'
down_revision: Union[str, Sequence[str], None] = '9d842e480345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_log_sessions', sa.Column('prior_period_adjustment', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('daily_log_sessions', sa.Column('adjustment_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_log_sessions', 'adjustment_notes')
    op.drop_column('daily_log_sessions', 'prior_period_adjustment')
    # ### end Alembic commands ###
