"""add_price_change_gain_loss_table_and_session_column

Revision ID: 9d842e480345
Revises: 6879ed34a91b
Create Date: 2026-07-18 11:30:06.878447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d842e480345'
down_revision: Union[str, Sequence[str], None] = '6879ed34a91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_change_gain_loss',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('opening_dip_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_sold_at_old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_at_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gain_loss_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['daily_log_sessions.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'tank_id', name='uq_session_tank_price_change')
    )
    op.create_index(op.f('ix_price_change_gain_loss_id'), 'price_change_gain_loss', ['id'], unique=False)
    op.add_column('daily_log_sessions', sa.Column('price_change_gain_loss_total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_log_sessions', 'price_change_gain_loss_total')
    op.drop_index(op.f('ix_price_change_gain_loss_id'), table_name='price_change_gain_loss')
    op.drop_table('price_change_gain_loss')
    # ### end Alembic commands ###
