"""Initial schema setup

Revision ID: a2d0b3b64af1
Revises: 
Create Date: 2026-06-23 21:41:37.128197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d0b3b64af1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_pumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_pumps_id'), 'fuel_pumps', ['id'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('current_outstanding_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_index(op.f('ix_credit_accounts_id'), 'credit_accounts', ['id'], unique=False)
    op.create_table('daily_financial_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_cash_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('digital_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_sales_logged', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_cash_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shortage_overage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pump_id', 'log_date', name='uq_pump_daily_financial_log')
    )
    op.create_index(op.f('ix_daily_financial_logs_id'), 'daily_financial_logs', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number_of_nozzles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("type IN ('CHARGE', 'PAYMENT')", name='chk_transaction_type'),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_table('product_price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_history_id'), 'product_price_history', ['id'], unique=False)
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanks_id'), 'tanks', ['id'], unique=False)
    op.create_table('daily_tank_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('testing_liters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_dip_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculated_variance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tank_id', 'log_date', name='uq_tank_daily_log')
    )
    op.create_index(op.f('ix_daily_tank_logs_id'), 'daily_tank_logs', ['id'], unique=False)
    op.create_table('nozzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nozzles_id'), 'nozzles', ['id'], unique=False)
    op.create_table('daily_nozzle_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nozzle_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_reset', sa.Boolean(), nullable=False),
    sa.Column('gross_liters_sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nozzle_id', 'log_date', name='uq_nozzle_daily_log')
    )
    op.create_index(op.f('ix_daily_nozzle_logs_id'), 'daily_nozzle_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_nozzle_logs_id'), table_name='daily_nozzle_logs')
    op.drop_table('daily_nozzle_logs')
    op.drop_index(op.f('ix_nozzles_id'), table_name='nozzles')
    op.drop_table('nozzles')
    op.drop_index(op.f('ix_daily_tank_logs_id'), table_name='daily_tank_logs')
    op.drop_table('daily_tank_logs')
    op.drop_index(op.f('ix_tanks_id'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_index(op.f('ix_product_price_history_id'), table_name='product_price_history')
    op.drop_table('product_price_history')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_daily_financial_logs_id'), table_name='daily_financial_logs')
    op.drop_table('daily_financial_logs')
    op.drop_index(op.f('ix_credit_accounts_id'), table_name='credit_accounts')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_fuel_pumps_id'), table_name='fuel_pumps')
    op.drop_table('fuel_pumps')
    # ### end Alembic commands ###
