"""add_log_date_to_daily_session_payments

Revision ID: beb4a7ad02c1
Revises: 390fc7b221bd
Create Date: 2026-07-04 18:46:08.650245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4a7ad02c1'
down_revision: Union[str, Sequence[str], None] = '390fc7b221bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('daily_session_payments', sa.Column('log_date', sa.Date(), nullable=True))
    op.execute("UPDATE daily_session_payments SET log_date = s.log_date FROM daily_log_sessions s WHERE daily_session_payments.session_id = s.id")
    op.alter_column('daily_session_payments', 'log_date', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_session_payments', 'log_date')
    # ### end Alembic commands ###
