"""add_pump_account_transactions_ledger

Revision ID: d8c5ca3d43ce
Revises: beb4a7ad02c1
Create Date: 2026-07-04 18:53:21.749671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c5ca3d43ce'
down_revision: Union[str, Sequence[str], None] = 'beb4a7ad02c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_account_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['pump_accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['daily_log_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pump_account_transactions_id'), 'pump_account_transactions', ['id'], unique=False)

    # Backfill: Insert historical IOCL transactions from closed sessions
    op.execute("""
        INSERT INTO pump_account_transactions (account_id, session_id, amount, log_date, description)
        SELECT
            pa.id,
            dls.id,
            SUM(dsp.amount),
            dls.log_date,
            'XTRA Power + XTRA Reward collections (backfill)'
        FROM daily_session_payments dsp
        JOIN daily_log_sessions dls ON dls.id = dsp.session_id
        JOIN pump_accounts pa ON pa.pump_id = dls.pump_id AND pa.name = 'IOCL Account'
        WHERE dls.status = 'CLOSED'
          AND dsp.payment_method IN ('XTRA Power', 'XTRA Reward')
        GROUP BY pa.id, dls.id, dls.log_date
        HAVING SUM(dsp.amount) > 0
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pump_account_transactions_id'), table_name='pump_account_transactions')
    op.drop_table('pump_account_transactions')
    # ### end Alembic commands ###
