"""Add product many-to-many, IST timezone, and transaction enum

Revision ID: d94020ade21a
Revises: a2d0b3b64af1
Create Date: 2026-06-23 22:07:26.198806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94020ade21a'
down_revision: Union[str, Sequence[str], None] = 'a2d0b3b64af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    credit_transaction_type = sa.Enum('CHARGE', 'PAYMENT', name='credit_transaction_type')
    credit_transaction_type.create(op.get_bind(), checkfirst=True)

    op.create_table('product_pumps',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'pump_id')
    )
    op.alter_column('credit_transactions', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CHARGE', 'PAYMENT', name='credit_transaction_type'),
               postgresql_using="type::credit_transaction_type",
               existing_nullable=False)
    op.drop_constraint(op.f('uq_pump_daily_financial_log'), 'daily_financial_logs', type_='unique')
    op.create_unique_constraint('uq_pump_daily_financial_log', 'daily_financial_logs', ['pump_id', 'log_timestamp'])
    op.drop_constraint(op.f('uq_nozzle_daily_log'), 'daily_nozzle_logs', type_='unique')
    op.create_unique_constraint('uq_nozzle_daily_log', 'daily_nozzle_logs', ['nozzle_id', 'log_timestamp'])
    op.drop_constraint(op.f('uq_tank_daily_log'), 'daily_tank_logs', type_='unique')
    op.create_unique_constraint('uq_tank_daily_log', 'daily_tank_logs', ['tank_id', 'log_timestamp'])
    op.drop_constraint(op.f('products_pump_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'pump_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('pump_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_pump_id_fkey'), 'products', 'fuel_pumps', ['pump_id'], ['id'])
    op.drop_constraint('uq_tank_daily_log', 'daily_tank_logs', type_='unique')
    op.create_unique_constraint(op.f('uq_tank_daily_log'), 'daily_tank_logs', ['tank_id', 'log_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_nozzle_daily_log', 'daily_nozzle_logs', type_='unique')
    op.create_unique_constraint(op.f('uq_nozzle_daily_log'), 'daily_nozzle_logs', ['nozzle_id', 'log_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_pump_daily_financial_log', 'daily_financial_logs', type_='unique')
    op.create_unique_constraint(op.f('uq_pump_daily_financial_log'), 'daily_financial_logs', ['pump_id', 'log_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('credit_transactions', 'type',
               existing_type=sa.Enum('CHARGE', 'PAYMENT', name='credit_transaction_type'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('product_pumps')
    # Drop the ENUM type
    sa.Enum(name='credit_transaction_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
